### ISSUE TITLE
Duplicates entire lines instead of only selection

### ISSUE THREAD

**Issue by poacher2k** [gregbacchus/vscode-duplicate#2]
Hi!

I've been enjoying this extension for a long time, and I really appreciate the work you've put into it.

Recently, I've noticed that when duplicating a selection, the entire line(s) where the selection starts and ends are duplicated in its entirety, instead of only the selection. See screencaps below:

Multi-line:

https://user-images.githubusercontent.com/2255960/156574158-547c4ee7-9615-444a-8e3b-edb9e1597802.mov

Single-line:

https://user-images.githubusercontent.com/2255960/156574508-d2a9e639-f56f-4dec-9f60-51667246e39f.mov

Again thank you for creating and maintaining this great extension :)

\- Daniel

**Comment by gregbacchus** [comment]
Hey Daniel
Thanks for taking the time to give feedback. It's always encouraging to hear that people are appreciating one's work.

With regards to this issue, I suspect that something has happened to change you key bindings. How we could test this would be to make the selection in the editor, and go to the command palette (depending on OS, something like Ctrl+Shift+P) and search for `Duplicate selection or line`. Execute it from there and see what the behavior is.

**Comment by poacher2k** [comment]
Thank you for the quick and helpful reply Greg! Apparently I had `Copy Line Down` on `Cmd+Shift+D` and your `Duplicate selection or line` on `Ctrl+Shift+D`, and I was repeatedly and consistently hitting the wrong shortcut. I removed the inferior `Copy Line Down`, and my muscle memory will adjust!

Big apologies for wasting your time, and bigger thanks for the reminder that the problem _usually_ sits between the chair and keyboard. Hope you have a great weekend!
